//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALLENAMENTO
    {
        public int IdSquadra { get; set; }
        public int IdPalestra { get; set; }
        public string Giorno { get; set; }
        public int Ora { get; set; }
    
        public virtual PALESTRA PALESTRA { get; set; }
        public virtual SQUADRA SQUADRA { get; set; }
    }
}
