//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUOTA
    {
        public int IdQuota { get; set; }
        public int anno { get; set; }
        public int costo { get; set; }
        public int IdGiocatore { get; set; }
        public int IdScontrino { get; set; }
    
        public virtual GIOCATORE GIOCATORE { get; set; }
        public virtual SCONTRINO SCONTRINO { get; set; }
    }
}
