//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATTREZZATURA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ATTREZZATURA()
        {
            this.PALESTRA = new HashSet<PALESTRA>();
        }
    
        public int IdAttrezzatura { get; set; }
        public string Descrizione { get; set; }
        public int Quantita { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PALESTRA> PALESTRA { get; set; }
    }
}
