//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIOCATORE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GIOCATORE()
        {
            this.CAMPO_ESTIVO = new HashSet<CAMPO_ESTIVO>();
            this.MATERIALE = new HashSet<MATERIALE>();
            this.SQUADRA = new HashSet<SQUADRA>();
            this.QUOTA = new HashSet<QUOTA>();
            this.STATISTICA_GIOCATORE = new HashSet<STATISTICA_GIOCATORE>();
        }
    
        public int IdGiocatore { get; set; }
        public string Nome { get; set; }
        public string Cognome { get; set; }
        public int Età { get; set; }
        public Nullable<int> Telefono { get; set; }
        public string E_mail { get; set; }
        public int NumeroMaglia { get; set; }
        public string CodiceFiscale { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAMPO_ESTIVO> CAMPO_ESTIVO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MATERIALE> MATERIALE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SQUADRA> SQUADRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUOTA> QUOTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STATISTICA_GIOCATORE> STATISTICA_GIOCATORE { get; set; }
    }
}
