//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATERIALE
    {
        public int idMateriale { get; set; }
        public string descrizione { get; set; }
        public int disponibilità { get; set; }
        public decimal prezzo { get; set; }
        public int IdGiocatore { get; set; }
        public int IdScontrino { get; set; }
    
        public virtual GIOCATORE GIOCATORE { get; set; }
        public virtual SCONTRINO SCONTRINO { get; set; }
    }
}
