//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PALESTRA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PALESTRA()
        {
            this.ALLENAMENTO = new HashSet<ALLENAMENTO>();
            this.CAMPO_ESTIVO = new HashSet<CAMPO_ESTIVO>();
        }
    
        public int IdPalestra { get; set; }
        public string Nome { get; set; }
        public string Indirizzo { get; set; }
        public int IdAttrezzatura { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ALLENAMENTO> ALLENAMENTO { get; set; }
        public virtual ATTREZZATURA ATTREZZATURA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAMPO_ESTIVO> CAMPO_ESTIVO { get; set; }
    }
}
