//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARTITA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PARTITA()
        {
            this.STATISTICA_GIOCATORE = new HashSet<STATISTICA_GIOCATORE>();
        }
    
        public int IdPartita { get; set; }
        public System.DateTime Data { get; set; }
        public System.TimeSpan Ora { get; set; }
        public string Avversiario { get; set; }
        public Nullable<int> PuntiFatti { get; set; }
        public Nullable<int> PuntiSubiti { get; set; }
        public int IdSquadra { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STATISTICA_GIOCATORE> STATISTICA_GIOCATORE { get; set; }
        public virtual SQUADRA SQUADRA { get; set; }
    }
}
