//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SQUADRA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SQUADRA()
        {
            this.ALLENAMENTO = new HashSet<ALLENAMENTO>();
            this.PARTITA = new HashSet<PARTITA>();
        }
    
        public int IdSquadra { get; set; }
        public string Nome { get; set; }
        public int Annata { get; set; }
        public int NumeroGiocatori { get; set; }
        public string Livello { get; set; }
        public int IdAllenatore { get; set; }
        public int IdGiocatore { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ALLENAMENTO> ALLENAMENTO { get; set; }
        public virtual ALLENATORE ALLENATORE { get; set; }
        public virtual GIOCATORE GIOCATORE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PARTITA> PARTITA { get; set; }
    }
}
