//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class STATISTICA_GIOCATORE
    {
        public Nullable<int> TirtiLiberi { get; set; }
        public Nullable<int> DuePunti { get; set; }
        public Nullable<int> TrePunti { get; set; }
        public Nullable<int> Falli { get; set; }
        public Nullable<int> Rimbalzi { get; set; }
        public Nullable<int> Recuperate { get; set; }
        public Nullable<int> Perse { get; set; }
        public int IdPartita { get; set; }
        public int IdGiocatore { get; set; }
    
        public virtual GIOCATORE GIOCATORE { get; set; }
        public virtual PARTITA PARTITA { get; set; }
    }
}
