//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAMPO_ESTIVO
    {
        public int IdCampoEstivo { get; set; }
        public int Anno { get; set; }
        public int Settimana { get; set; }
        public string Descrizione { get; set; }
        public int IdAllenatore { get; set; }
        public int IdGiocatore { get; set; }
        public int IdPalestra { get; set; }
    
        public virtual ALLENATORE ALLENATORE { get; set; }
        public virtual GIOCATORE GIOCATORE { get; set; }
        public virtual PALESTRA PALESTRA { get; set; }
    }
}
