//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp.model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseEntities : DbContext
    {
        public DatabaseEntities()
            : base("name=DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ALLENAMENTO> ALLENAMENTO { get; set; }
        public virtual DbSet<ALLENATORE> ALLENATORE { get; set; }
        public virtual DbSet<ATTREZZATURA> ATTREZZATURA { get; set; }
        public virtual DbSet<CAMPO_ESTIVO> CAMPO_ESTIVO { get; set; }
        public virtual DbSet<GIOCATORE> GIOCATORE { get; set; }
        public virtual DbSet<MATERIALE> MATERIALE { get; set; }
        public virtual DbSet<PALESTRA> PALESTRA { get; set; }
        public virtual DbSet<PARTITA> PARTITA { get; set; }
        public virtual DbSet<QUOTA> QUOTA { get; set; }
        public virtual DbSet<SCONTRINO> SCONTRINO { get; set; }
        public virtual DbSet<SQUADRA> SQUADRA { get; set; }
        public virtual DbSet<STATISTICA_GIOCATORE> STATISTICA_GIOCATORE { get; set; }
    }
}
